#spring.application.name=renukiran-services
#
## HTTPS Configuration
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
##server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tomcat
#
## HTTP Configuration - redirect to HTTPS
#server.http2.enabled=true

spring.application.name=renukiran-services

# For basic functionality, we can use HTTP in local development

# HTTP Configuration for local development
server.port=8080

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:19239/railway
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=oILEjdkCOUSbzqTVXOTeCqrhgDXKyukG
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable H2 console when using Postgres
spring.h2.console.enabled=false

