#spring.application.name=renukiran-services
#
## HTTPS Configuration
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
##server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tomcat
#
## HTTP Configuration - redirect to HTTPS
#server.http2.enabled=true

spring.application.name=renukiran-services

# For basic functionality, we can use HTTP in local development

# HTTP Configuration for local development
server.port=8080
server.ssl.enabled=false
server.http2.enabled=true


